### ISSUE TITLE
Mod doesn't let the game launch.

### ISSUE THREAD

**Issue by Nordblum** [bluedoom/DSP_Mod#1]
Here's an output of Bepinex console when trying to launch the game with just this one mod installed. These messages are spammed non-stop, the game loading doesn't go past "Almost there..."
![unknown](https://user-images.githubusercontent.com/10522412/110701362-1e032480-8202-11eb-947d-0b053a298667.png)

**Comment by bluedoom** [comment]
I can't get useful info from these log(maybe you need to cap the first error log).Have you tried intsall the mod on a pure game? Maybe it conflict with some other mods.

**Comment by Nordblum** [comment]
Tried creating a profile with just this mod installed (and bepinex because it's required).
![image](https://user-images.githubusercontent.com/10522412/110734513-06935e00-8239-11eb-98e3-ee5c50a3762b.png)
The same thing happens again - game is stuck at LOADING - Almost there.
Here's LogOutput.log after launching the game and having it stuck at Almost there. The last error messages are repeated many times per second:
﻿[Message:   BepInEx] BepInEx 5.4.5.0 - DSPGAME
[Info   :   BepInEx] Running under Unity v2018.4.12.5889476
[Info   :   BepInEx] CLR runtime version: 2.0.50727.1433
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 1 plugins to load
[Info   :   BepInEx] Loading [CompressSave 1.0]
[Message:   BepInEx] Chainloader startup complete
[Warning:CompressSave] GameSave Start
[Error  : Unity Log] EntryPointNotFoundException: No matching entry point found for CalCompressOutBufferSize in LZ4.LZ4API
Stack trace:
MonoMod.Utils.DynDll.InternalResolveDynDllImports (System.Type type, System.Object instance, System.Collections.Generic.Dictionary`2 mappings)
MonoMod.Utils.DynDll.ResolveDynDllImports (System.Type type, System.Collections.Generic.Dictionary`2 mappings)
LZ4.LZ4API..cctor ()
Rethrow as TypeInitializationException: An exception was thrown by the type initializer for LZ4.LZ4API
LZ4.LZ4CompressionStream.CreateBuffer (Int32 ExBufferSize)
DSP_Plugin.PatchSave..cctor ()
Rethrow as TypeInitializationException: An exception was thrown by the type initializer for DSP_Plugin.PatchSave
(wrapper dynamic-method) GameSave.DMD<GameSave..LoadCurrentGame> (string) <0x00073>
GameSave.LoadCurrentGameInResource (int) <0x00258>
GameMain.Start () <0x001b6>

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
GameMain.LateUpdate ()

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
GameCamera.Logic ()
GameCamera.FrameLogic ()
GameCamera.LateUpdate ()

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
GameMain.LateUpdate ()

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
GameCamera.Logic ()
GameCamera.FrameLogic ()
GameCamera.LateUpdate ()

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
GameMain.LateUpdate ()

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
GameCamera.Logic ()
GameCamera.FrameLogic ()
GameCamera.LateUpdate ()

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
GameMain.LateUpdate ()

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
GameCamera.Logic ()
GameCamera.FrameLogic ()
GameCamera.LateUpdate ()

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
GameMain.LateUpdate ()

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
GameCamera.Logic ()
GameCamera.FrameLogic ()
GameCamera.LateUpdate ()

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
GameMain.LateUpdate ()

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
GameCamera.Logic ()
GameCamera.FrameLogic ()
GameCamera.LateUpdate ()

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
GameMain.LateUpdate ()

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
GameCamera.Logic ()
GameCamera.FrameLogic ()
GameCamera.LateUpdate ()

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
GameMain.LateUpdate ()

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
GameCamera.Logic ()
GameCamera.FrameLogic ()
GameCamera.LateUpdate ()

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
GuideMissionStandardMode.Skip (.GameData _gameData)
GameData.SkipStandardModeGuide ()
GameLoader.FixedUpdate ()

**Comment by bluedoom** [comment]
there is a temporary solution, unzip the mod file into "Dyson Sphere Program/BepInEx/plugins". I'll try to fixed the problem later.

**Comment by Nordblum** [comment]
Doesn't help, console is full of errors and the game won't load.
![image](https://user-images.githubusercontent.com/10522412/110762171-90572180-8261-11eb-9fe6-4a72cbd7ad11.png)

**Comment by bluedoom** [comment]
> Doesn't help, console is full of errors and the game won't load.
> ![image](https://user-images.githubusercontent.com/10522412/110762171-90572180-8261-11eb-9fe6-4a72cbd7ad11.png)

Sorry, it does not work with r2modman at present.

**Comment by bluedoom** [comment]
Bug fixed
