### ISSUE TITLE
无法加载压缩存档以及解压后的压缩存档

### ISSUE THREAD

**Issue by yumozzz** [bluedoom/DSP_Mod#10]
存档版本0.9.24.11209
可能和mod有关，以下是mod列表
xiaoye97-BepInEx-5.4.17
Allz-EnableMilkyWayGalaxy-1.1.1
kumor-AutoBuild-1.0.4
brokenmass-RailgunsRetargeting-1.3.3
Cyh-AutoStellarNavigation-1.0.4
GreyHak-DSP_Belt_Reverse_Direction-1.1.5
brotchie-MinerInfo-1.0.1
blacksnipebiu-Multfuntion_mod-2.0.8
PhantomGamers-IlLine-1.0.0
nebula-NebulaMultiplayerModApi-1.1.2
nebula-NebulaMultiplayerMod-0.7.10//没有开
CommonAPI-CommonAPI-1.3.4
xiaoye97-LDBTool-2.0.5
kremnev8-BlueprintTweaks-1.4.1
aekoch-UnlimitedFoundations-1.0.1
CommonAPI-DSPModSave-1.1.3
Shad0wlife-AssemblerUI-2.2.1
Gimbalhawk-AutoLogisticsDroneSetup-1.4.1
bluedoom-CompressSave-1.1.8
blacksnipebiu-Auxilaryfunction-1.4.7
HarriXS-More_Replication-1.3.1
testpushpleaseignore-Power_Network_Manager-0.0.6//没有开
Raptor-UncoverFoundationedOceans-0.0.1
brokenmass-BetterStats-1.3.3
Semar-Bottleneck-0.1.4
目前存档大小1.5g（一天前，正常保存）/1.9g（解压）（中间我没有做出很大的改变）
报错信息（压缩和压缩后解压的存档报错相同）：
游戏运行错误！存档文件版本不兼容或者已经损坏。
EndOfStreamExteption:Unable to read beyond the end of the stream.
System.IO.BinaryReader.ReadByte ()(at address)
MethaAppearance.Import(System.IO.BinaryReader r)(at address)
Mecha.Import(System.IO.BinaryReader r)(at address)
Player.Import(System.IO.BinaryReader r)(at address)
Gamedata.Import(System.IO.BinaryReader r)(at address)
Gamesave.LoadCurrentGame(System.String saveName)(at address)
UnityEngine.Debug:LogException(Exception)
GameSave.LoadCurrentGame(String)
GameMain:Start()

**Comment by bluedoom** [comment]
> 建议退回老版本试试，能解压出来说明压缩过程没有出问题。目前没有收到过和其他Mod冲突的消息。

**Comment by bluedoom** [comment]
看这个 #10
