### ISSUE TITLE
机甲DIY系统问题导致坏档能恢复么

### ISSUE THREAD

**Issue by cenzhe** [bluedoom/DSP_Mod#11]
看到1.1.9中因为DIY系统问题暂时关闭了压缩存档，想问下存档能恢复么？上一次备份的非压缩存档在30小时前了，求一个恢复工具，或者指点下怎么能手动恢复也行

**Comment by bluedoom** [comment]
应该还有救，我研究研究

**Comment by bluedoom** [comment]
#10

**Comment by bluedoom** [comment]
https://github.com/bluedoom/DSP_Mod/releases/tag/1.1.10
