### ISSUE TITLE
Current latest release not functioning in latest DSP version

### ISSUE THREAD

**Issue by explodoboy** [bluedoom/DSP_Mod#8]
The current latest version of CompressSave, 1.1.7, is not working with the latest version of Dyson Sphere Program (0.9.24.11209)

It seems that the entire mod is broken. Compressed saves cannot be loaded, compressed saves cannot be decompressed.

Reinstalling a compatible version of Dyson Sphere Program (0.8.x), decompressing the save, and then reinstalling latest version (0.9.24.11029) and loading the decompressed save does NOT work. Loading the save into the latest version (0.9.24.11029) results in an error, the save not loading, and the game needing to be restarted.

**Comment by bluedoom** [comment]
e4823f9

**Comment by explodoboy** [comment]
Thank you for updating the mod so fast! I really appreciate it. I can confirm that the mod is now working without any issues.
